/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface;

import business.VendorCatalog;
import business.VendorCatalogDirectory;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Chintan
 */
public class AddVendorJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private VendorCatalogDirectory vendorCatalogDirectory;
    /**
     * Creates new form AddVendorJPanel
     */
    public AddVendorJPanel(JPanel userProcessContainer, VendorCatalogDirectory vendorCatalogDirectory) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.vendorCatalogDirectory=vendorCatalogDirectory;   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        txtVendorName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();

        jLabel1.setText("Vendor Name:");

        btnSubmit.setText("SUBMIT");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Add a Vendor");

        btnBack.setText("< BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(28, 28, 28)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnSubmit)
                                .addComponent(txtVendorName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addGap(178, 178, 178)))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtVendorName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSubmit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBack)
                .addContainerGap(149, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
      userProcessContainer.remove(this);
      Component[] componentArray = userProcessContainer.getComponents();
      Component component = componentArray[componentArray.length - 1];
      ManageVendorsJPanel manageVendorsJPanel = (ManageVendorsJPanel) component;
      manageVendorsJPanel.populateTable();
      CardLayout layout = (CardLayout) userProcessContainer.getLayout();
      layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        String vendorName=txtVendorName.getText();
        
        if(vendorName.isEmpty()||vendorName.startsWith(" ")){
            JOptionPane.showMessageDialog(this, "Vendor Name is mandatory!!!");
            return;
        }
        
        String VendorNamePattern = "[a-zA-Z ]+";
        Pattern patternLName = Pattern.compile(VendorNamePattern);
        Matcher matchLName = patternLName.matcher(txtVendorName.getText());
        if (!matchLName.matches()) {
            JOptionPane.showMessageDialog(this, "Please enter only alphabets in vendor's name!!");
            return;
        } else {
        }

        for (VendorCatalog vendorCatalog : vendorCatalogDirectory.getVendorsList()) {
            if (txtVendorName.getText().equals(vendorCatalog.getVendorName())) {
                JOptionPane.showMessageDialog(this, "Vendor Already exists!!!", "ERROR", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
        
        VendorCatalog vendorCatalog = vendorCatalogDirectory.addVendorCatalog();

        vendorCatalog.setVendorName(vendorName);
        JOptionPane.showMessageDialog(this, "Vendor Name added successfully!!!");
        txtVendorName.setText("");
    }//GEN-LAST:event_btnSubmitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtVendorName;
    // End of variables declaration//GEN-END:variables
}
