/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface;

import business.Resume;
import business.ResumeHistory;
import java.awt.Image;
import java.io.File;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Chintan
 */
public class CreateResumeJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateResumeJPanel
     */
    private ResumeHistory rh;

    //Radio buttons and image variables
    String fileName;
    String genderTemp;
    String countryTemp;
    String certificationTemp;

    ButtonGroup country = new ButtonGroup();
    ButtonGroup gender = new ButtonGroup();
    ButtonGroup graduation = new ButtonGroup();

    //Variables for programming checkboxes
    String prog1 = "";
    String prog2 = "";
    String prog3 = "";
    String prog4 = "";
    String prog5 = "";
    String prog6 = "";
    String prog7 = "";
    String prog8 = "";

    //Variables for Softwares checkboxes
    String soft1 = "";
    String soft2 = "";
    String soft3 = "";
    String soft4 = "";
    String soft5 = "";
    String soft6 = "";
    String soft7 = "";
    String soft8 = "";

    public CreateResumeJPanel(ResumeHistory rh) {
        initComponents();
        submitBtn.setVisible(false);
        this.rh = rh;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblFirstName = new javax.swing.JLabel();
        firstNameTxtField = new javax.swing.JTextField();
        lblLastName = new javax.swing.JLabel();
        lastNameTxtField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        lblStreetLn1 = new javax.swing.JLabel();
        streetLn1TxtField = new javax.swing.JTextField();
        lblStreetLn2 = new javax.swing.JLabel();
        streetLn2TxtField = new javax.swing.JTextField();
        lblCity = new javax.swing.JLabel();
        cityTxtField = new javax.swing.JTextField();
        lblCountry = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblAffiliation = new javax.swing.JLabel();
        affiliationTxtField = new javax.swing.JTextField();
        lblCarObjStatement = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblDegreeUndergrad = new javax.swing.JLabel();
        degree1TxtField = new javax.swing.JTextField();
        lblDegreeUndergradDate = new javax.swing.JLabel();
        degree1DateTextField = new javax.swing.JTextField();
        lblDegreeGrad = new javax.swing.JLabel();
        degree2TxtField = new javax.swing.JTextField();
        lblDegreeGradDate = new javax.swing.JLabel();
        degree2DateTextField = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        lblTotalExp = new javax.swing.JLabel();
        totalExpTxtField = new javax.swing.JTextField();
        lblProgLang = new javax.swing.JLabel();
        lblSoftware = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        lblEmailId = new javax.swing.JLabel();
        emailIdTxtField = new javax.swing.JTextField();
        lblContactNumber = new javax.swing.JLabel();
        submitBtn = new javax.swing.JButton();
        browseImageBtn = new javax.swing.JButton();
        imgLabel = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        carObjStatTxtField = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        imagePathTxtField = new javax.swing.JTextArea();
        confirmCheckBox = new javax.swing.JCheckBox();
        contactNumberTxtField = new javax.swing.JTextField();
        checkboxProg2 = new javax.swing.JCheckBox();
        checkboxProg3 = new javax.swing.JCheckBox();
        checkboxProg1 = new javax.swing.JCheckBox();
        checkboxProg4 = new javax.swing.JCheckBox();
        checkboxProg5 = new javax.swing.JCheckBox();
        checkboxProg6 = new javax.swing.JCheckBox();
        checkboxProg7 = new javax.swing.JCheckBox();
        checkboxProg8 = new javax.swing.JCheckBox();
        checkboxSoft1 = new javax.swing.JCheckBox();
        checkboxSoft2 = new javax.swing.JCheckBox();
        checkboxSoft3 = new javax.swing.JCheckBox();
        checkboxSoft4 = new javax.swing.JCheckBox();
        checkboxSoft5 = new javax.swing.JCheckBox();
        checkboxSoft6 = new javax.swing.JCheckBox();
        checkboxSoft7 = new javax.swing.JCheckBox();
        checkboxSoft8 = new javax.swing.JCheckBox();
        lblGender = new javax.swing.JLabel();
        btnMale = new javax.swing.JRadioButton();
        btnFemale = new javax.swing.JRadioButton();
        btnCountryUsa = new javax.swing.JRadioButton();
        btnCountryIntl = new javax.swing.JRadioButton();
        lblCertifications = new javax.swing.JLabel();
        btnGradYes = new javax.swing.JRadioButton();
        btnGradNo = new javax.swing.JRadioButton();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("CREATE A RESUME");

        jLabel2.setFont(new java.awt.Font("Georgia", 3, 12)); // NOI18N
        jLabel2.setText("NAME");

        lblFirstName.setText("First Name:");

        lblLastName.setText("Last Name:");

        jLabel5.setFont(new java.awt.Font("Georgia", 3, 12)); // NOI18N
        jLabel5.setText("ADDRESS");

        lblStreetLn1.setText("Street Line 1:");

        lblStreetLn2.setText("Street Line 2:");

        lblCity.setText("City:");

        lblCountry.setText("Country:");

        jLabel10.setFont(new java.awt.Font("Georgia", 3, 12)); // NOI18N
        jLabel10.setText("BRIEF SUMMARY");

        lblAffiliation.setText("Affiliation:");

        lblCarObjStatement.setText("Carrier Objective Statement:");

        jLabel13.setFont(new java.awt.Font("Georgia", 3, 12)); // NOI18N
        jLabel13.setText("EDUCATION");

        lblDegreeUndergrad.setText("Degree 1 (UNDERGRADUATE):");

        lblDegreeUndergradDate.setText("Degree 1 Completion Date: (MM/YYYY)");

        lblDegreeGrad.setText("Degree 2 (GRADUATE):");

        lblDegreeGradDate.setText("Degree 2 Completion Date:(MM/YYYY)");

        jLabel18.setFont(new java.awt.Font("Georgia", 3, 12)); // NOI18N
        jLabel18.setText("WORK EXPERIENCE");

        lblTotalExp.setText("Total Experience (In Years):");

        lblProgLang.setText("Programming Languages Known:");

        lblSoftware.setText("Softwares Worked On:");

        jLabel22.setFont(new java.awt.Font("Georgia", 3, 12)); // NOI18N
        jLabel22.setText("CONTACT DETAILS");

        lblEmailId.setText("Email-Id:");

        lblContactNumber.setText("Contact Number:");

        submitBtn.setText("Submit Response");
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });

        browseImageBtn.setText("BROWSE IMAGE");
        browseImageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseImageBtnActionPerformed(evt);
            }
        });

        carObjStatTxtField.setColumns(20);
        carObjStatTxtField.setLineWrap(true);
        carObjStatTxtField.setRows(5);
        jScrollPane3.setViewportView(carObjStatTxtField);

        imagePathTxtField.setEditable(false);
        imagePathTxtField.setColumns(20);
        imagePathTxtField.setLineWrap(true);
        imagePathTxtField.setRows(5);
        jScrollPane5.setViewportView(imagePathTxtField);

        confirmCheckBox.setText("I, hereby certify, all the above mentioned information is true to the best of my knowledge.");
        confirmCheckBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                confirmCheckBoxItemStateChanged(evt);
            }
        });

        checkboxProg2.setText(".NET");
        checkboxProg2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkboxProg2ItemStateChanged(evt);
            }
        });

        checkboxProg3.setText("JAVASCRIPT");
        checkboxProg3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkboxProg3ItemStateChanged(evt);
            }
        });

        checkboxProg1.setText("CORE JAVA");
        checkboxProg1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkboxProg1ItemStateChanged(evt);
            }
        });

        checkboxProg4.setText("C#");
        checkboxProg4.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkboxProg4ItemStateChanged(evt);
            }
        });

        checkboxProg5.setText("C/C++");
        checkboxProg5.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkboxProg5ItemStateChanged(evt);
            }
        });

        checkboxProg6.setText("PYTHON");
        checkboxProg6.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkboxProg6ItemStateChanged(evt);
            }
        });

        checkboxProg7.setText("SQL");
        checkboxProg7.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkboxProg7ItemStateChanged(evt);
            }
        });

        checkboxProg8.setText("RUBY\\RAILS");
        checkboxProg8.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkboxProg8ItemStateChanged(evt);
            }
        });

        checkboxSoft1.setText("VISUAL STUDIO");
        checkboxSoft1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkboxSoft1ItemStateChanged(evt);
            }
        });

        checkboxSoft2.setText("ECLIPSE");
        checkboxSoft2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkboxSoft2ItemStateChanged(evt);
            }
        });

        checkboxSoft3.setText("NETBEANS");
        checkboxSoft3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkboxSoft3ItemStateChanged(evt);
            }
        });

        checkboxSoft4.setText("MATLAB");
        checkboxSoft4.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkboxSoft4ItemStateChanged(evt);
            }
        });

        checkboxSoft5.setText("ORACLE");
        checkboxSoft5.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkboxSoft5ItemStateChanged(evt);
            }
        });

        checkboxSoft6.setText("POSTGRE-SQL");
        checkboxSoft6.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkboxSoft6ItemStateChanged(evt);
            }
        });

        checkboxSoft7.setText("Tortoise Git");
        checkboxSoft7.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkboxSoft7ItemStateChanged(evt);
            }
        });

        checkboxSoft8.setText("MS-OFFICE");
        checkboxSoft8.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkboxSoft8ItemStateChanged(evt);
            }
        });

        lblGender.setText("Gender:");

        btnMale.setText("MALE");
        btnMale.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                btnMaleStateChanged(evt);
            }
        });

        btnFemale.setText("FEMALE");
        btnFemale.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                btnFemaleStateChanged(evt);
            }
        });

        btnCountryUsa.setText("USA");
        btnCountryUsa.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                btnCountryUsaStateChanged(evt);
            }
        });

        btnCountryIntl.setText("INTERNATIONAL");
        btnCountryIntl.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                btnCountryIntlStateChanged(evt);
            }
        });

        lblCertifications.setText("ANY CERTIFICATIONS TILL DATE?");

        btnGradYes.setText("YES");
        btnGradYes.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                btnGradYesStateChanged(evt);
            }
        });

        btnGradNo.setText("NO");
        btnGradNo.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                btnGradNoStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(413, 413, 413)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(lblStreetLn2, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(streetLn2TxtField))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(lblStreetLn1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(18, 18, 18)
                                            .addComponent(streetLn1TxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblGender, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnMale, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnFemale, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(lblLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(lastNameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(lblFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(firstNameTxtField)))
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(210, 210, 210)
                                .addComponent(imgLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(630, 630, 630)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblCity, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lblCountry, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(btnCountryUsa)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnCountryIntl, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(cityTxtField)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblAffiliation, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(affiliationTxtField))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblCarObjStatement, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPane3)))
                                .addGap(237, 237, 237)
                                .addComponent(browseImageBtn))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblDegreeGrad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblDegreeUndergrad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblSoftware, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblProgLang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblCertifications, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblTotalExp)
                                    .addComponent(jLabel18))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(checkboxSoft5, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(checkboxSoft6, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(checkboxSoft1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(checkboxSoft2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(checkboxProg5, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, Short.MAX_VALUE)
                                        .addComponent(checkboxProg6, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(checkboxProg1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, Short.MAX_VALUE)
                                        .addComponent(checkboxProg2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnGradYes)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnGradNo))
                                    .addComponent(degree2TxtField)
                                    .addComponent(degree1TxtField)
                                    .addComponent(totalExpTxtField))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(checkboxProg7, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(checkboxProg3, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(checkboxSoft3, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(checkboxSoft7, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(checkboxSoft8, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(checkboxSoft4, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(checkboxProg8, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(checkboxProg4, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblDegreeGradDate)
                                            .addComponent(lblDegreeUndergradDate))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(degree1DateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(degree2DateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(submitBtn)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(confirmCheckBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblContactNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(contactNumberTxtField))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblEmailId, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(emailIdTxtField)))))))
                .addContainerGap(484, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lastNameTxtField, streetLn1TxtField});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCountryIntl, btnCountryUsa, btnFemale, btnGradNo, btnGradYes, btnMale});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFirstName)
                            .addComponent(firstNameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblLastName)
                            .addComponent(lastNameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblGender)
                            .addComponent(btnMale)
                            .addComponent(btnFemale))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblStreetLn1)
                            .addComponent(streetLn1TxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblStreetLn2)
                            .addComponent(streetLn2TxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(imgLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCity)
                            .addComponent(cityTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCountry)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnCountryUsa)
                                .addComponent(btnCountryIntl))))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(browseImageBtn))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(affiliationTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAffiliation))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCarObjStatement)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(degree1TxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(degree1DateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblDegreeUndergradDate))
                    .addComponent(lblDegreeUndergrad))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblCertifications)
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(degree2TxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblDegreeGradDate)
                                .addComponent(degree2DateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblDegreeGrad)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnGradYes)
                        .addComponent(btnGradNo)))
                .addGap(18, 18, 18)
                .addComponent(jLabel18)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblTotalExp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(checkboxProg2)
                                    .addComponent(checkboxProg3)
                                    .addComponent(checkboxProg1)
                                    .addComponent(checkboxProg4))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(checkboxProg5)
                                    .addComponent(checkboxProg6)
                                    .addComponent(checkboxProg7)
                                    .addComponent(checkboxProg8))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(checkboxSoft1)
                                    .addComponent(checkboxSoft2)
                                    .addComponent(checkboxSoft3)
                                    .addComponent(checkboxSoft4)
                                    .addComponent(lblSoftware))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(checkboxSoft5)
                                    .addComponent(checkboxSoft6)
                                    .addComponent(checkboxSoft7)
                                    .addComponent(checkboxSoft8)))
                            .addComponent(lblProgLang))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(jLabel22))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(totalExpTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEmailId)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(emailIdTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(contactNumberTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblContactNumber))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(confirmCheckBox)
                .addGap(26, 26, 26)
                .addComponent(submitBtn)
                .addGap(20, 20, 20))
        );

        jScrollPane4.setViewportView(jPanel1);

        add(jScrollPane4, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void confirmCheckBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_confirmCheckBoxItemStateChanged
        // TODO add your handling code here:
        if (confirmCheckBox.isSelected()) {
            submitBtn.setVisible(true);
        } else {
            submitBtn.setVisible(false);
        }
    }//GEN-LAST:event_confirmCheckBoxItemStateChanged

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        // TODO add your handling code here:

        String firstName = firstNameTxtField.getText();
        String lastName = lastNameTxtField.getText();
        String streetLn1 = streetLn1TxtField.getText();
        String streetLn2 = streetLn2TxtField.getText();
        String city = cityTxtField.getText();
        String affiliation = affiliationTxtField.getText();
        String carObjStatement = carObjStatTxtField.getText();
        String degreeUndergrad = degree1TxtField.getText();
        String degreeUndergradDate = degree1DateTextField.getText();
        String emailId = emailIdTxtField.getText();
        String degreeGrad = degree2TxtField.getText();
        String degreeGradDate = degree2DateTextField.getText();

        //Radio Buttons code
        graduation.add(btnGradYes);
        graduation.add(btnGradNo);

        gender.add(btnMale);
        gender.add(btnFemale);

        country.add(btnCountryUsa);
        country.add(btnCountryIntl);

        //Temporary String for validations of total experience and contact number
        String tempContactNumber;
        tempContactNumber = contactNumberTxtField.getText();

        String tempTotalExp;
        tempTotalExp = totalExpTxtField.getText();

        if (firstName.isEmpty() || firstName.startsWith(" ") || lastName.isEmpty() || lastName.startsWith(" ")
                || streetLn1.isEmpty() || streetLn1.startsWith(" ") || city.isEmpty() || city.startsWith(" ")
                || affiliation.isEmpty() || affiliation.startsWith(" ") || carObjStatement.isEmpty()
                || carObjStatement.startsWith(" ") || degreeUndergrad.isEmpty() || degreeUndergrad.startsWith(" ")
                || degreeUndergradDate.isEmpty() || degreeUndergradDate.startsWith(" ")
                || degreeGrad.isEmpty() || degreeGrad.startsWith(" ")
                || degreeGradDate.isEmpty() || degreeGradDate.startsWith(" ")
                || (!(btnGradYes.isSelected() || btnGradNo.isSelected()))
                || (!(btnMale.isSelected() || btnFemale.isSelected()))
                || (!(btnCountryUsa.isSelected() || btnCountryIntl.isSelected()))
                || (tempContactNumber.trim().length() != 10) || (tempTotalExp.startsWith(" "))) {
            JOptionPane.showMessageDialog(this, "All fields are mandatory!!! (make sure you dont start with spaces!)");
            return;
        }

        //Validating first and last name
        String firstNamePattern = "[a-zA-Z ]+";
        Pattern patternFName = Pattern.compile(firstNamePattern);
        Matcher matchFName = patternFName.matcher(firstNameTxtField.getText());
        if (!matchFName.matches()) {
            JOptionPane.showMessageDialog(this, "Please enter only alphabets in first name!!");
            return;
        } else {
        }

        String lastNamePattern = "[a-zA-Z ]+";
        Pattern patternLName = Pattern.compile(lastNamePattern);
        Matcher matchLName = patternLName.matcher(firstNameTxtField.getText());
        if (!matchLName.matches()) {
            JOptionPane.showMessageDialog(this, "Please enter only alphabets in first name!!");
            return;
        } else {
        }

        //Validating dates
        String datePattern = "((0[1-9])|(1[0-2]))\\/(\\d{4})";
        Pattern patternDate = Pattern.compile(datePattern);
        Matcher matchDate1 = patternDate.matcher(degree1DateTextField.getText());
        Matcher matchDate2 = patternDate.matcher(degree2DateTextField.getText());
        if ((!matchDate1.matches()) || (!matchDate2.matches())) {
            JOptionPane.showMessageDialog(this, "Please enter date in given format!!");
            return;
        } else {
        }

        //Validations for Total experience
        int totalExperience = 0;
        Long contactNumber = Long.parseLong("0000000000");

        if (tempTotalExp.length() != 0) {
            try {
                totalExperience = Integer.parseInt(totalExpTxtField.getText());
                if (totalExperience > 50 || totalExperience < 0) {
                    JOptionPane.showMessageDialog(this, "Total experience should be between 0 and 50");
                    return;
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Total experience can contain only numbers!");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Total experience cannot be empty!!");
            return;
        }

        //Validations for Contact Number
        if (tempContactNumber.length() != 0) {
            try {
                int contactNumberLength = 0;
                contactNumber = Long.parseLong(contactNumberTxtField.getText());
                contactNumberLength = contactNumber.toString().length();
                if (contactNumber < 0 || contactNumberLength != 10) {
                    JOptionPane.showMessageDialog(this, "Contact number should be positive and of 10 digits!!");
                    return;
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Contact Number should contain only numbers!");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Contact Number cannot be empty!!(Make sure format is proper)");
            return;
        }

        //Adding to resume history
        Resume resume = rh.addResume();

        resume.setFirstName(firstName);
        resume.setLastName(lastName);
        resume.setStreetLn1(streetLn1);
        resume.setStreetLn2(streetLn2);
        resume.setCity(city);
        resume.setAffiliation(affiliation);
        resume.setCarrierObjectiveStatement(carObjStatement);
        resume.setDegree1(degreeUndergrad);
        resume.setDegree1Date(degreeUndergradDate);
        resume.setTotalExperience(totalExperience);
        resume.setEmailId(emailId);
        resume.setContactNumber(contactNumber);
        resume.setDegree2(degreeGrad);
        resume.setDegree2Date(degreeGradDate);

        resume.setFilePath(fileName);//Path for Image
        resume.setGender(genderTemp);
        resume.setCountry(countryTemp);
        resume.setProgrammingKnowledge(progCheckboxString());
        resume.setSoftwareKnownledge(softCheckboxString());
        JOptionPane.showMessageDialog(null, "Resume Added Successully");
        resetFields();  //to reset the entire form
    }//GEN-LAST:event_submitBtnActionPerformed

    private void resetFields() {
        firstNameTxtField.setText("");
        lastNameTxtField.setText("");
        streetLn1TxtField.setText("");
        streetLn2TxtField.setText("");
        cityTxtField.setText("");
        affiliationTxtField.setText("");
        carObjStatTxtField.setText("");
        degree1TxtField.setText("");
        degree1DateTextField.setText("");
        degree2TxtField.setText("");
        degree2DateTextField.setText("");
        totalExpTxtField.setText("");
        emailIdTxtField.setText("");
        contactNumberTxtField.setText("");

        //Radio buttons reset
        gender.clearSelection();
        country.clearSelection();
        graduation.clearSelection();

        //Image reset
        imagePathTxtField.setText("");
        ImageIcon icon = new ImageIcon("");
        imgLabel.setIcon(new ImageIcon(icon.getImage().getScaledInstance(160, 195, Image.SCALE_DEFAULT)));

        //confirm check box reset
        confirmCheckBox.setSelected(false);

        //Programming Checkbox reset
        checkboxProg1.setSelected(false);
        checkboxProg2.setSelected(false);
        checkboxProg3.setSelected(false);
        checkboxProg4.setSelected(false);
        checkboxProg5.setSelected(false);
        checkboxProg6.setSelected(false);
        checkboxProg7.setSelected(false);
        checkboxProg8.setSelected(false);

        //Software Checkbox reset
        checkboxSoft1.setSelected(false);
        checkboxSoft2.setSelected(false);
        checkboxSoft3.setSelected(false);
        checkboxSoft4.setSelected(false);
        checkboxSoft5.setSelected(false);
        checkboxSoft6.setSelected(false);
        checkboxSoft7.setSelected(false);
        checkboxSoft8.setSelected(false);
    }

    private String progCheckboxString() {
        StringBuffer builder = new StringBuffer();
        if (prog1 != "") {
            builder = builder.append(prog1);
        }

        if (prog2 != "") {
            builder.append(prog2);
        }

        if (prog3 != "") {
            builder.append(prog3);
        }

        if (prog4 != "") {
            builder.append(prog4);
        }

        if (prog5 != "") {
            builder.append(prog5);
        }

        if (prog6 != "") {
            builder.append(prog6);
        }

        if (prog7 != "") {
            builder.append(prog7);
        }

        if (prog8 != "") {
            builder.append(prog8);
        }
        int temp_builder = builder.length();
        if (temp_builder > 0) {
            builder = builder.deleteCharAt(0);
        }
        return builder.toString();
    }

    private String softCheckboxString() {
        StringBuffer builder_soft = new StringBuffer();
        if (soft1 != "") {
            builder_soft = builder_soft.append(soft1);
        }

        if (soft2 != "") {
            builder_soft.append(soft2);
        }

        if (soft3 != "") {
            builder_soft.append(soft3);
        }

        if (soft4 != "") {
            builder_soft.append(soft4);
        }

        if (soft5 != "") {
            builder_soft.append(soft5);
        }

        if (soft6 != "") {
            builder_soft.append(soft6);
        }

        if (soft7 != "") {
            builder_soft.append(soft7);
        }

        if (soft8 != "") {
            builder_soft.append(soft8);
        }
        int temp_builder_soft = builder_soft.length();
        if (temp_builder_soft > 0) {
            builder_soft = builder_soft.deleteCharAt(0);
        }
        return builder_soft.toString();
    }

    private void browseImageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseImageBtnActionPerformed
        // TODO add your handling code here:
        JFileChooser chooseImage = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("JPG Images", "jpg");
        chooseImage.setAcceptAllFileFilterUsed(false);
        chooseImage.setFileFilter(filter);
        int returnVal = chooseImage.showOpenDialog(null);

        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File f = chooseImage.getSelectedFile();
            fileName = f.getAbsolutePath();
            imagePathTxtField.setText(fileName);
            ImageIcon icon = new ImageIcon(fileName);
            imgLabel.setIcon(new ImageIcon(icon.getImage().getScaledInstance(160, 195, Image.SCALE_DEFAULT)));
        }
    }//GEN-LAST:event_browseImageBtnActionPerformed

    private void btnGradYesStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_btnGradYesStateChanged
        // TODO add your handling code here:
        if (btnGradYes.isSelected()) {
            btnGradNo.setSelected(false);
            certificationTemp = "YES";
        } else {
        }

    }//GEN-LAST:event_btnGradYesStateChanged

    private void btnGradNoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_btnGradNoStateChanged
        // TODO add your handling code here:
        if (btnGradNo.isSelected()) {
            //flag = 0;
            btnGradYes.setSelected(false);
            certificationTemp = "NO";
        } else {

        }

    }//GEN-LAST:event_btnGradNoStateChanged

    private void btnMaleStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_btnMaleStateChanged
        // TODO add your handling code here:
        if (btnMale.isSelected()) {
            btnFemale.setSelected(false);
            genderTemp = "Male";

        } else {

        }
    }//GEN-LAST:event_btnMaleStateChanged

    private void btnFemaleStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_btnFemaleStateChanged
        // TODO add your handling code here:
        if (btnFemale.isSelected()) {
            btnMale.setSelected(false);
            genderTemp = "Female";
        } else {

        }
    }//GEN-LAST:event_btnFemaleStateChanged

    private void btnCountryUsaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_btnCountryUsaStateChanged
        // TODO add your handling code here:
        if (btnCountryUsa.isSelected()) {
            btnCountryIntl.setSelected(false);
            countryTemp = "USA";

        } else {

        }
    }//GEN-LAST:event_btnCountryUsaStateChanged

    private void btnCountryIntlStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_btnCountryIntlStateChanged
        // TODO add your handling code here:
        if (btnCountryIntl.isSelected()) {
            btnCountryUsa.setSelected(false);
            countryTemp = "International";

        } else {

        }
    }//GEN-LAST:event_btnCountryIntlStateChanged

    private void checkboxProg1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkboxProg1ItemStateChanged
        // TODO add your handling code here:
        if (checkboxProg1.isSelected()) {
            prog1 = ",CORE JAVA ";
        } else {
            prog1 = "";
        }
    }//GEN-LAST:event_checkboxProg1ItemStateChanged

    private void checkboxProg2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkboxProg2ItemStateChanged
        // TODO add your handling code here:
        if (checkboxProg2.isSelected()) {
            prog2 = ",.NET ";
        } else {
            prog2 = "";
        }
    }//GEN-LAST:event_checkboxProg2ItemStateChanged

    private void checkboxProg3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkboxProg3ItemStateChanged
        // TODO add your handling code here:
        if (checkboxProg3.isSelected()) {
            prog3 = ",JAVASCRIPT ";
        } else {
            prog3 = "";
        }
    }//GEN-LAST:event_checkboxProg3ItemStateChanged

    private void checkboxProg4ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkboxProg4ItemStateChanged
        // TODO add your handling code here:
        if (checkboxProg4.isSelected()) {
            prog4 = ",C# ";
        } else {
            prog4 = "";
        }
    }//GEN-LAST:event_checkboxProg4ItemStateChanged

    private void checkboxProg5ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkboxProg5ItemStateChanged
        // TODO add your handling code here:
        if (checkboxProg5.isSelected()) {
            prog5 = ",C/C++ ";
        } else {
            prog5 = "";
        }
    }//GEN-LAST:event_checkboxProg5ItemStateChanged

    private void checkboxProg6ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkboxProg6ItemStateChanged
        // TODO add your handling code here:
        if (checkboxProg6.isSelected()) {
            prog6 = ",PYTHON ";
        } else {
            prog6 = "";
        }
    }//GEN-LAST:event_checkboxProg6ItemStateChanged

    private void checkboxProg7ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkboxProg7ItemStateChanged
        // TODO add your handling code here:
        if (checkboxProg7.isSelected()) {
            prog7 = ",SQL ";
        } else {
            prog7 = "";
        }
    }//GEN-LAST:event_checkboxProg7ItemStateChanged

    private void checkboxProg8ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkboxProg8ItemStateChanged
        // TODO add your handling code here:
        if (checkboxProg8.isSelected()) {
            prog8 = ",RUBY/RAILS ";
        } else {
            prog8 = "";
        }
    }//GEN-LAST:event_checkboxProg8ItemStateChanged

    private void checkboxSoft1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkboxSoft1ItemStateChanged
        // TODO add your handling code here:
        if (checkboxSoft1.isSelected()) {
            soft1 = ",VISUAL STUDIO ";
        } else {
            soft1 = "";
        }
    }//GEN-LAST:event_checkboxSoft1ItemStateChanged

    private void checkboxSoft2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkboxSoft2ItemStateChanged
        // TODO add your handling code here:
        if (checkboxSoft2.isSelected()) {
            soft2 = ",ECLIPSE ";
        } else {
            soft2 = "";
        }
    }//GEN-LAST:event_checkboxSoft2ItemStateChanged

    private void checkboxSoft3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkboxSoft3ItemStateChanged
        // TODO add your handling code here:
        if (checkboxSoft3.isSelected()) {
            soft3 = ",NETBEANS ";
        } else {
            soft3 = "";
        }
    }//GEN-LAST:event_checkboxSoft3ItemStateChanged

    private void checkboxSoft4ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkboxSoft4ItemStateChanged
        // TODO add your handling code here:
        if (checkboxSoft4.isSelected()) {
            soft4 = ",MATLAB ";
        } else {
            soft4 = "";
        }
    }//GEN-LAST:event_checkboxSoft4ItemStateChanged

    private void checkboxSoft5ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkboxSoft5ItemStateChanged
        // TODO add your handling code here:
        if (checkboxSoft5.isSelected()) {
            soft5 = ",ORACLE ";
        } else {
            soft5 = "";
        }
    }//GEN-LAST:event_checkboxSoft5ItemStateChanged

    private void checkboxSoft6ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkboxSoft6ItemStateChanged
        // TODO add your handling code here:
        if (checkboxSoft6.isSelected()) {
            soft6 = ",POSTGRE-SQL ";
        } else {
            soft6 = "";
        }
    }//GEN-LAST:event_checkboxSoft6ItemStateChanged

    private void checkboxSoft7ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkboxSoft7ItemStateChanged
        // TODO add your handling code here:
        if (checkboxSoft7.isSelected()) {
            soft7 = ",Tortoise Git ";
        } else {
            soft7 = "";
        }
    }//GEN-LAST:event_checkboxSoft7ItemStateChanged

    private void checkboxSoft8ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkboxSoft8ItemStateChanged
        // TODO add your handling code here:
        if (checkboxSoft8.isSelected()) {
            soft8 = ",MS-OFFICE ";
        } else {
            soft8 = "";
        }
    }//GEN-LAST:event_checkboxSoft8ItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField affiliationTxtField;
    private javax.swing.JButton browseImageBtn;
    private javax.swing.JRadioButton btnCountryIntl;
    private javax.swing.JRadioButton btnCountryUsa;
    private javax.swing.JRadioButton btnFemale;
    private javax.swing.JRadioButton btnGradNo;
    private javax.swing.JRadioButton btnGradYes;
    private javax.swing.JRadioButton btnMale;
    private javax.swing.JTextArea carObjStatTxtField;
    private javax.swing.JCheckBox checkboxProg1;
    private javax.swing.JCheckBox checkboxProg2;
    private javax.swing.JCheckBox checkboxProg3;
    private javax.swing.JCheckBox checkboxProg4;
    private javax.swing.JCheckBox checkboxProg5;
    private javax.swing.JCheckBox checkboxProg6;
    private javax.swing.JCheckBox checkboxProg7;
    private javax.swing.JCheckBox checkboxProg8;
    private javax.swing.JCheckBox checkboxSoft1;
    private javax.swing.JCheckBox checkboxSoft2;
    private javax.swing.JCheckBox checkboxSoft3;
    private javax.swing.JCheckBox checkboxSoft4;
    private javax.swing.JCheckBox checkboxSoft5;
    private javax.swing.JCheckBox checkboxSoft6;
    private javax.swing.JCheckBox checkboxSoft7;
    private javax.swing.JCheckBox checkboxSoft8;
    private javax.swing.JTextField cityTxtField;
    private javax.swing.JCheckBox confirmCheckBox;
    private javax.swing.JTextField contactNumberTxtField;
    private javax.swing.JTextField degree1DateTextField;
    private javax.swing.JTextField degree1TxtField;
    private javax.swing.JTextField degree2DateTextField;
    private javax.swing.JTextField degree2TxtField;
    private javax.swing.JTextField emailIdTxtField;
    private javax.swing.JTextField firstNameTxtField;
    private javax.swing.JTextArea imagePathTxtField;
    private javax.swing.JLabel imgLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextField lastNameTxtField;
    private javax.swing.JLabel lblAffiliation;
    private javax.swing.JLabel lblCarObjStatement;
    private javax.swing.JLabel lblCertifications;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblContactNumber;
    private javax.swing.JLabel lblCountry;
    private javax.swing.JLabel lblDegreeGrad;
    private javax.swing.JLabel lblDegreeGradDate;
    private javax.swing.JLabel lblDegreeUndergrad;
    private javax.swing.JLabel lblDegreeUndergradDate;
    private javax.swing.JLabel lblEmailId;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblProgLang;
    private javax.swing.JLabel lblSoftware;
    private javax.swing.JLabel lblStreetLn1;
    private javax.swing.JLabel lblStreetLn2;
    private javax.swing.JLabel lblTotalExp;
    private javax.swing.JTextField streetLn1TxtField;
    private javax.swing.JTextField streetLn2TxtField;
    private javax.swing.JButton submitBtn;
    private javax.swing.JTextField totalExpTxtField;
    // End of variables declaration//GEN-END:variables
}
