/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface;

import business.Resume;
import business.ResumeHistory;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Chintan
 */
public class DisplayResumeJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DisplayResumeJPanel
     */
    private ResumeHistory rh;

    public DisplayResumeJPanel(ResumeHistory rh) {
        initComponents();
        this.rh = rh;
        populateTable();
    }

    public void populateTable() {
        DefaultTableModel dtm = (DefaultTableModel) tblResumeList.getModel();
        dtm.setRowCount(0);

        for (Resume resume : rh.getResumeHistory()) {
            Object row[] = new Object[3];
            row[0] = resume;
            row[1] = resume.getLastName();
            row[2] = resume.getContactNumber();
            dtm.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lblDegreeGrad = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblFirstName = new javax.swing.JLabel();
        firstNameTxtField = new javax.swing.JTextField();
        lblLastName = new javax.swing.JLabel();
        lastNameTxtField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        lblStreetLn1 = new javax.swing.JLabel();
        streetLn1TxtField = new javax.swing.JTextField();
        lblStreetLn2 = new javax.swing.JLabel();
        streetLn2TxtField = new javax.swing.JTextField();
        lblCity = new javax.swing.JLabel();
        cityTxtField = new javax.swing.JTextField();
        lblCountry = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblAffiliation = new javax.swing.JLabel();
        affiliationTxtField = new javax.swing.JTextField();
        lblCarObjStatement = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblDegreeUndergrad = new javax.swing.JLabel();
        degree1TxtField = new javax.swing.JTextField();
        lblDegreeUndergradDate = new javax.swing.JLabel();
        degree1DateTextField = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        degree2TxtField = new javax.swing.JTextField();
        lblDegreeGradDate = new javax.swing.JLabel();
        degree2DateTextField = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        lblTotalExp = new javax.swing.JLabel();
        totalExpTxtField = new javax.swing.JTextField();
        lblProgLangKnown = new javax.swing.JLabel();
        lblSoftwareKnown = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        lblEmailId = new javax.swing.JLabel();
        emailIdTxtField = new javax.swing.JTextField();
        lblContactNumber = new javax.swing.JLabel();
        imgLabel = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        carObjStatTxtField = new javax.swing.JTextArea();
        contactNumberTxtField = new javax.swing.JTextField();
        lblGender = new javax.swing.JLabel();
        lblCertifications = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblResumeList = new javax.swing.JTable();
        jLabel27 = new javax.swing.JLabel();
        btnViewResume = new javax.swing.JButton();
        btnDeleteResume = new javax.swing.JButton();
        graduationTxtField = new javax.swing.JTextField();
        genderTextField = new javax.swing.JTextField();
        countryTxtField = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        progKnownTxtField = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        softKnownTextField = new javax.swing.JTextArea();

        setLayout(new java.awt.BorderLayout());

        lblDegreeGrad.setBackground(new java.awt.Color(255, 255, 255));
        lblDegreeGrad.setEnabled(false);

        jLabel2.setFont(new java.awt.Font("Georgia", 3, 12)); // NOI18N
        jLabel2.setText("NAME");

        lblFirstName.setText("First Name:");

        firstNameTxtField.setEditable(false);
        firstNameTxtField.setEnabled(false);

        lblLastName.setText("Last Name:");

        lastNameTxtField.setEditable(false);
        lastNameTxtField.setEnabled(false);

        jLabel5.setFont(new java.awt.Font("Georgia", 3, 12)); // NOI18N
        jLabel5.setText("ADDRESS");

        lblStreetLn1.setText("Street Line 1:");

        streetLn1TxtField.setEditable(false);
        streetLn1TxtField.setEnabled(false);

        lblStreetLn2.setText("Street Line 2:");

        streetLn2TxtField.setEditable(false);
        streetLn2TxtField.setEnabled(false);

        lblCity.setText("City:");

        cityTxtField.setEditable(false);
        cityTxtField.setEnabled(false);

        lblCountry.setText("Country:");

        jLabel10.setFont(new java.awt.Font("Georgia", 3, 12)); // NOI18N
        jLabel10.setText("BRIEF SUMMARY");

        lblAffiliation.setText("Affiliation:");

        affiliationTxtField.setEditable(false);
        affiliationTxtField.setEnabled(false);

        lblCarObjStatement.setText("Carrier Objective Statement:");

        jLabel13.setFont(new java.awt.Font("Georgia", 3, 12)); // NOI18N
        jLabel13.setText("EDUCATION");

        lblDegreeUndergrad.setText("Degree 1 (UNDERGRADUATE):");

        degree1TxtField.setEditable(false);
        degree1TxtField.setEnabled(false);

        lblDegreeUndergradDate.setText("Degree 1 Completion Date:");

        degree1DateTextField.setEditable(false);
        degree1DateTextField.setEnabled(false);

        jLabel16.setText("Degree 2 (GRADUATE):");

        degree2TxtField.setEditable(false);
        degree2TxtField.setEnabled(false);

        lblDegreeGradDate.setText("Degree 2 Completion Date:");

        degree2DateTextField.setEditable(false);
        degree2DateTextField.setEnabled(false);

        jLabel18.setFont(new java.awt.Font("Georgia", 3, 12)); // NOI18N
        jLabel18.setText("WORK EXPERIENCE");

        lblTotalExp.setText("Total Experience (In Years):");

        totalExpTxtField.setEditable(false);
        totalExpTxtField.setEnabled(false);

        lblProgLangKnown.setText("Programming Languages Known:");

        lblSoftwareKnown.setText("Softwares Worked On:");

        jLabel22.setFont(new java.awt.Font("Georgia", 3, 12)); // NOI18N
        jLabel22.setText("CONTACT DETAILS");

        lblEmailId.setText("Email-Id:");

        emailIdTxtField.setEditable(false);
        emailIdTxtField.setEnabled(false);

        lblContactNumber.setText("Contact Number:");

        carObjStatTxtField.setEditable(false);
        carObjStatTxtField.setBackground(new java.awt.Color(240, 240, 240));
        carObjStatTxtField.setColumns(20);
        carObjStatTxtField.setLineWrap(true);
        carObjStatTxtField.setRows(5);
        carObjStatTxtField.setEnabled(false);
        jScrollPane3.setViewportView(carObjStatTxtField);

        contactNumberTxtField.setEditable(false);
        contactNumberTxtField.setEnabled(false);

        lblGender.setText("Gender:");

        lblCertifications.setText("ANY CERTIFICATIONS TILL DATE?");

        tblResumeList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "First Name", "Last Name", "Contact Number"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblResumeList.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tblResumeList);

        jLabel27.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel27.setText("LIST OF RESUMES CREATED:");

        btnViewResume.setText("VIEW RESUME");
        btnViewResume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewResumeActionPerformed(evt);
            }
        });

        btnDeleteResume.setText("DELETE RESUME");
        btnDeleteResume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteResumeActionPerformed(evt);
            }
        });

        graduationTxtField.setEditable(false);
        graduationTxtField.setEnabled(false);

        genderTextField.setEditable(false);
        genderTextField.setEnabled(false);

        countryTxtField.setEditable(false);
        countryTxtField.setEnabled(false);

        progKnownTxtField.setEditable(false);
        progKnownTxtField.setBackground(new java.awt.Color(240, 240, 240));
        progKnownTxtField.setColumns(20);
        progKnownTxtField.setLineWrap(true);
        progKnownTxtField.setRows(5);
        jScrollPane4.setViewportView(progKnownTxtField);

        softKnownTextField.setEditable(false);
        softKnownTextField.setBackground(new java.awt.Color(240, 240, 240));
        softKnownTextField.setColumns(20);
        softKnownTextField.setLineWrap(true);
        softKnownTextField.setRows(5);
        jScrollPane5.setViewportView(softKnownTextField);

        javax.swing.GroupLayout lblDegreeGradLayout = new javax.swing.GroupLayout(lblDegreeGrad);
        lblDegreeGrad.setLayout(lblDegreeGradLayout);
        lblDegreeGradLayout.setHorizontalGroup(
            lblDegreeGradLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblDegreeGradLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(lblDegreeGradLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 663, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(lblDegreeGradLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, lblDegreeGradLayout.createSequentialGroup()
                            .addComponent(lblContactNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(contactNumberTxtField, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, lblDegreeGradLayout.createSequentialGroup()
                            .addComponent(lblEmailId, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(emailIdTxtField)))
                    .addGroup(lblDegreeGradLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(lblDegreeGradLayout.createSequentialGroup()
                            .addGroup(lblDegreeGradLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblCity, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(lblDegreeGradLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblCountry, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(18, 18, 18)
                            .addGroup(lblDegreeGradLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cityTxtField, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                                .addComponent(countryTxtField)))
                        .addGroup(lblDegreeGradLayout.createSequentialGroup()
                            .addComponent(lblAffiliation, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(affiliationTxtField))
                        .addGroup(lblDegreeGradLayout.createSequentialGroup()
                            .addComponent(lblCarObjStatement, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jScrollPane3)))
                    .addGroup(lblDegreeGradLayout.createSequentialGroup()
                        .addGroup(lblDegreeGradLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnViewResume, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(lblDegreeGradLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(lblDegreeGradLayout.createSequentialGroup()
                                    .addComponent(lblStreetLn2, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(streetLn2TxtField))
                                .addGroup(lblDegreeGradLayout.createSequentialGroup()
                                    .addGroup(lblDegreeGradLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(lblStreetLn1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addComponent(streetLn1TxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(lblDegreeGradLayout.createSequentialGroup()
                                    .addComponent(lblGender, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(genderTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(lblDegreeGradLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(lblDegreeGradLayout.createSequentialGroup()
                                        .addComponent(lblLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lastNameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, lblDegreeGradLayout.createSequentialGroup()
                                        .addComponent(lblFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(firstNameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(lblDegreeGradLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(lblDegreeGradLayout.createSequentialGroup()
                                .addGap(210, 210, 210)
                                .addComponent(imgLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lblDegreeGradLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnDeleteResume)
                                .addGap(171, 171, 171))))
                    .addGroup(lblDegreeGradLayout.createSequentialGroup()
                        .addGroup(lblDegreeGradLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(lblDegreeGradLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblDegreeUndergrad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblSoftwareKnown, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblProgLangKnown, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblCertifications, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblTotalExp)
                            .addComponent(jLabel18))
                        .addGap(18, 18, 18)
                        .addGroup(lblDegreeGradLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(lblDegreeGradLayout.createSequentialGroup()
                                .addGroup(lblDegreeGradLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(totalExpTxtField)
                                    .addComponent(degree2TxtField)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lblDegreeGradLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(degree1TxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(graduationTxtField)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(lblDegreeGradLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDegreeGradDate)
                                    .addComponent(lblDegreeUndergradDate))
                                .addGap(18, 18, 18)
                                .addGroup(lblDegreeGradLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(degree1DateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(degree2DateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(lblDegreeGradLayout.createSequentialGroup()
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(819, 819, 819))
        );

        lblDegreeGradLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnDeleteResume, btnViewResume});

        lblDegreeGradLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cityTxtField, lastNameTxtField, streetLn1TxtField});

        lblDegreeGradLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jScrollPane4, jScrollPane5});

        lblDegreeGradLayout.setVerticalGroup(
            lblDegreeGradLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblDegreeGradLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel27)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(lblDegreeGradLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnViewResume)
                    .addComponent(btnDeleteResume))
                .addGap(100, 100, 100)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(lblDegreeGradLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lblDegreeGradLayout.createSequentialGroup()
                        .addGroup(lblDegreeGradLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFirstName)
                            .addComponent(firstNameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(lblDegreeGradLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblLastName)
                            .addComponent(lastNameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(lblDegreeGradLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblGender)
                            .addComponent(genderTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addGroup(lblDegreeGradLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblStreetLn1)
                            .addComponent(streetLn1TxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(lblDegreeGradLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblStreetLn2)
                            .addComponent(streetLn2TxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(imgLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(lblDegreeGradLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCity)
                    .addComponent(cityTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(lblDegreeGradLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCountry)
                    .addComponent(countryTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addGroup(lblDegreeGradLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(affiliationTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAffiliation))
                .addGap(18, 18, 18)
                .addGroup(lblDegreeGradLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCarObjStatement)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addGroup(lblDegreeGradLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lblDegreeGradLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(degree1TxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(degree1DateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblDegreeUndergradDate))
                    .addComponent(lblDegreeUndergrad))
                .addGap(18, 18, 18)
                .addGroup(lblDegreeGradLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCertifications)
                    .addComponent(graduationTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(lblDegreeGradLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(degree2TxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(degree2DateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDegreeGradDate)
                    .addGroup(lblDegreeGradLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel18)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(lblDegreeGradLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lblDegreeGradLayout.createSequentialGroup()
                        .addComponent(totalExpTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(lblDegreeGradLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblProgLangKnown)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblTotalExp))
                .addGap(18, 18, 18)
                .addGroup(lblDegreeGradLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSoftwareKnown)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel22)
                .addGap(18, 18, 18)
                .addGroup(lblDegreeGradLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEmailId)
                    .addGroup(lblDegreeGradLayout.createSequentialGroup()
                        .addComponent(emailIdTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(lblDegreeGradLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(contactNumberTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblContactNumber))))
                .addGap(71, 71, 71))
        );

        lblDegreeGradLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jScrollPane3, jScrollPane4, jScrollPane5});

        jScrollPane1.setViewportView(lblDegreeGrad);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewResumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewResumeActionPerformed
        // TODO add your handling code here:
        int selectedrow = tblResumeList.getSelectedRow();

        if (selectedrow >= 0) {
            Resume resume = (Resume) tblResumeList.getValueAt(selectedrow, 0);

            firstNameTxtField.setText(resume.getFirstName());
            lastNameTxtField.setText(resume.getLastName());
            streetLn1TxtField.setText(resume.getStreetLn1());
            streetLn2TxtField.setText(resume.getStreetLn2());
            cityTxtField.setText(resume.getCity());
            affiliationTxtField.setText(resume.getAffiliation());
            carObjStatTxtField.setText(resume.getCarrierObjectiveStatement());
            degree1TxtField.setText(resume.getDegree1());
            degree1DateTextField.setText(resume.getDegree1Date());
            String filePath = resume.getFilePath();
            genderTextField.setText(resume.getGender());
            countryTxtField.setText(resume.getCountry());
            imgLabel.setIcon(new ImageIcon(new ImageIcon(filePath).getImage().getScaledInstance(160, 195, Image.SCALE_DEFAULT)));

            //For radio Buttons to Text Fields
            progKnownTxtField.setText(resume.getProgrammingKnowledge());
            softKnownTextField.setText(resume.getSoftwareKnownledge());

            //For Graduation 
            graduationTxtField.setText("Yes");
            degree2TxtField.setText(resume.getDegree2());
            degree2DateTextField.setText(resume.getDegree2Date());

            totalExpTxtField.setText(String.valueOf(resume.getTotalExperience()));
            emailIdTxtField.setText(resume.getEmailId());
            contactNumberTxtField.setText(String.valueOf(resume.getContactNumber()));
        } else {
            JOptionPane.showMessageDialog(null, "Please select any row!");
        }
    }//GEN-LAST:event_btnViewResumeActionPerformed

    private void resetFields() {
        firstNameTxtField.setText("");
        lastNameTxtField.setText("");
        streetLn1TxtField.setText("");
        streetLn2TxtField.setText("");
        cityTxtField.setText("");
        affiliationTxtField.setText("");
        carObjStatTxtField.setText("");
        degree1TxtField.setText("");
        degree1DateTextField.setText("");
        degree2TxtField.setText("");
        degree2DateTextField.setText("");
        totalExpTxtField.setText("");
        emailIdTxtField.setText("");
        contactNumberTxtField.setText("");
        ImageIcon icon = new ImageIcon("");
        progKnownTxtField.setText("");
        softKnownTextField.setText("");
        genderTextField.setText("");
        countryTxtField.setText("");
        graduationTxtField.setText("");
        imgLabel.setIcon(new ImageIcon(icon.getImage().getScaledInstance(160, 195, Image.SCALE_DEFAULT)));
    }

    private void btnDeleteResumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteResumeActionPerformed
        // TODO add your handling code here:
        int selectedrow = tblResumeList.getSelectedRow();
        if (selectedrow >= 0) {
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete selected resume?", "Delete Confirmation", dialogButton);
            if (dialogResult == 0) {
                Resume resume = (Resume) tblResumeList.getValueAt(selectedrow, 0);
                rh.deleteResume(resume);
                JOptionPane.showMessageDialog(this, "Resume has been deleted!!");
                populateTable();
                resetFields();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please select any row!");
        }
    }//GEN-LAST:event_btnDeleteResumeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField affiliationTxtField;
    private javax.swing.JButton btnDeleteResume;
    private javax.swing.JButton btnViewResume;
    private javax.swing.JTextArea carObjStatTxtField;
    private javax.swing.JTextField cityTxtField;
    private javax.swing.JTextField contactNumberTxtField;
    private javax.swing.JTextField countryTxtField;
    private javax.swing.JTextField degree1DateTextField;
    private javax.swing.JTextField degree1TxtField;
    private javax.swing.JTextField degree2DateTextField;
    private javax.swing.JTextField degree2TxtField;
    private javax.swing.JTextField emailIdTxtField;
    private javax.swing.JTextField firstNameTxtField;
    private javax.swing.JTextField genderTextField;
    private javax.swing.JTextField graduationTxtField;
    private javax.swing.JLabel imgLabel;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextField lastNameTxtField;
    private javax.swing.JLabel lblAffiliation;
    private javax.swing.JLabel lblCarObjStatement;
    private javax.swing.JLabel lblCertifications;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblContactNumber;
    private javax.swing.JLabel lblCountry;
    private javax.swing.JPanel lblDegreeGrad;
    private javax.swing.JLabel lblDegreeGradDate;
    private javax.swing.JLabel lblDegreeUndergrad;
    private javax.swing.JLabel lblDegreeUndergradDate;
    private javax.swing.JLabel lblEmailId;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblProgLangKnown;
    private javax.swing.JLabel lblSoftwareKnown;
    private javax.swing.JLabel lblStreetLn1;
    private javax.swing.JLabel lblStreetLn2;
    private javax.swing.JLabel lblTotalExp;
    private javax.swing.JTextArea progKnownTxtField;
    private javax.swing.JTextArea softKnownTextField;
    private javax.swing.JTextField streetLn1TxtField;
    private javax.swing.JTextField streetLn2TxtField;
    private javax.swing.JTable tblResumeList;
    private javax.swing.JTextField totalExpTxtField;
    // End of variables declaration//GEN-END:variables
}
